### ISSUE TITLE
Table of Content issues with Wikipedia

### ISSUE THREAD

**Issue by GutHib** [aarddict/android#114]
There are obvious issues with the Table of Contents when using the German version of the Wikipedia on the most recent version of Aarddict (1.6.11). In most articles, the TOC doesn't appear at all, in some (try country articles, like "Belgien") the TOC appears as a tiny scrambled blob underneath the country fact box.

What I haven't tested:
- I don't know if the problem also occurred with previous versions of Aarddict
- I don't know if the problem occurs with the English language Wikipedia as well (too large for my phone)

What I have tested:
- Problem occurs with BOTH German Wikipedia version downloadable on the Aarddict main page (the one with the Magnet link and the one by MHBraun - so unless they are both from the same source, this would point to a problem with Aarddict rather than with the respective files)
- Problem does NOT occur with the English or German version of Wikivoyage (downloadable on that same page) - which, on the other hand, point to a problem with the Wikipedia files rather than with Aarddict :-)

**Comment by itkach** [comment]
Content issue, not application bug
