### ISSUE TITLE
"Not a dictionary file"

### ISSUE THREAD

**Issue by akorn** [aarddict/android#115]
Hi,

I have tried to download and use https://drive.google.com/file/d/0B8ENyWhpePB8N1czcHd0bzBDZUE/view?usp=sharing as well as https://drive.google.com/file/d/0B8ENyWhpePB8cHVqdnphUE11WlE/view?usp=sharing on a Oneplus One.

The aard app I got from F-Droid opens neither, complaining "not a dictionary file". I tried downloading the files with Chrome on the phone itself, as well as using firefox on a desktop and then using adb push to copy them to the phone.

Looking at the files using less(1), they definitely look like .slob files, and the size looks correct. At least in the case of the wordnet dictionary the sha1sum matches the one given at https://github.com/itkach/slob/wiki/Dictionaries.

**Comment by itkach** [comment]
Aard Dictionary does not work with .slob, only .aar dictionaries. You need
Aard 2, see http://aarddict.org

**Comment by akorn** [comment]
Oh. Silly me.

OTOH, the old app *does* send me to the page with the .slob dictionaries; and while the page does include a link to download old-style dictionaries, it wasn't clear to me as a first-time user that that's what I should do.

I'll give aard2 a try.

Thanks!
