### ISSUE TITLE
What are the required .aar files for aarddict?

### ISSUE THREAD

**Issue by codeparadox** [aarddict/android#116]
I checked the wikipedia english dump which is about 14GB (which will take days to download) and opening it with utorrent I saw there are 4 or 5 seperate files. Do I have to download them all to aarddict to be functional or can I download just the 2GB file alone? (or one from that bunch of 5?) 

Here is the link 

http://aarddict.org/1/index.html

**Comment by itkach** [comment]
I'm not sure what you mean by "functional". You can download just one file and open it but you'll get some random portion of Wikipedia content. Also, consider using Aard 2 (.slob files) which offers smaller (more compressed) dictionaries. You may want to check out "popular articles" version (https://github.com/itkach/slob/wiki/Dictionaries#popular-articles) if you're looking for a smaller download, but those are not as fresh as complete version.

**Comment by codeparadox** [comment]
Got it! fired up pc and checked the file and saw they all are chunks of a large file. so most popular will be my bet.
