### ISSUE TITLE
Request for inclusion in Fdroid

### ISSUE THREAD

**Issue by ageru** [aarddict/android#118]
Hi there,

Would it be OK if I requested inclusion of the app in [Fdroid](https://f-droid.org/wiki/page/Main_Page)?

Let me know if that would be a problem for you, or if I missed something and it doesn't qualify with their [Inclusion Policy](https://f-droid.org/wiki/page/Inclusion_Policy)...

Many thanks.

**Comment by itkach** [comment]
I don't mind, but this app is [already in F-Droid](https://f-droid.org/repository/browse/?fdfilter=aard&fdid=aarddict.android), and it is also old/obsolete. Perhaps you meant [Aard 2](https://github.com/itkach/aard2-android)? See also https://github.com/itkach/slobber/issues/1

**Comment by ageru** [comment]
May apologies. Not only did I completely confused the 2 repos, but I didn't even do my homework and look if this was already being worked on.

Looking forward to see the app in Fdroid soon :)

Kind regards.

**Comment by itkach** [comment]
@ageru no problem

> this was already being worked on.

looks like that effort is stalled
